In [29]:
# Import required libraries
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
import pandas as pd 
import numpy as np

In [41]:
# Load the data
data = pd.read_csv('../raw_data/brain_proteomics_data.csv')
data.head(5)

,Case,years_to_birth,gender,histological_type,race,ethnicity,radiation_therapy,Grade,Mutation.Count,Percent.aneuploidy,...,p27_p,p27_pT157_p,p27_pT198_p,p38_pT180_Y182_p,p53_p,p62-LCK-ligand_p,p70S6K_p,p70S6K_pT389_p,p90RSK_p,p90RSK_pT359_S363_p
0,TCGA-CS-4938,31,female,astrocytoma,white,not hispanic or latino,no,G2,15,0.069412,...,-0.425127,-0.033398,0.289192,1.060163,-0.407456,-0.470354,-0.107559,-0.060441,-0.053104,-0.011132
1,TCGA-CS-6665,51,female,astrocytoma,white,not hispanic or latino,yes,G3,75,0.524814,...,0.076536,0.011809,-0.047973,-0.054275,-0.244020,0.106282,-0.034369,0.585072,0.431720,-0.201412
2,TCGA-CS-6666,22,male,astrocytoma,white,not hispanic or latino,yes,G3,18,0.403165,...,0.110268,0.066886,-0.066150,0.250434,0.432187,-0.210412,0.290949,-0.893383,-0.693677,-0.055250
3,TCGA-DB-5270,38,female,oligoastrocytoma,white,not hispanic or latino,no,G3,16,0.061382,...,-0.235321,0.015372,-0.127422,-1.190789,0.105396,0.218569,-0.099136,1.990618,0.166788,-0.235380
4,TCGA-DB-5273,33,male,astrocytoma,white,not hispanic or latino,yes,G3,16,0.017349,...,-0.343212,-0.250564,-0.234582,0.648598,-0.071851,-0.041811,-0.099300,-0.920359,-0.243159,-0.128841

In [42]:
data.outcome.value_counts()

outcome
1    184
0    122
Name: count, dtype: int64

In [43]:
data.rename(columns={'outcome': 'class'}, inplace=True)

In [44]:
data.dtypes

Case                    object
years_to_birth           int64
gender                  object
histological_type       object
race                    object
                        ...
p62-LCK-ligand_p       float64
p70S6K_p               float64
p70S6K_pT389_p         float64
p90RSK_p               float64
p90RSK_pT359_S363_p    float64
Length: 186, dtype: object

In [34]:
# Create X and y
# X is only the columns of proteins, 'years_to_birth','gender', remain

data['gender'] = data['gender'].map({'male':0,'female':1})

X = data.drop(columns =['Case','histological_type','race','ethnicity','radiation_therapy','Grade','Mutation.Count','Percent.aneuploidy','IDH.status','class'])
y = data['class']

In [45]:
data['gender'] = data['gender'].map({'male':0,'female':1})

X = data.drop(columns =['Case','years_to_birth','gender','histological_type','race','ethnicity','radiation_therapy','Grade','Mutation.Count','Percent.aneuploidy','IDH.status','class'])
y = data['class']

In [46]:
# Split train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [50]:
tpot = TPOTClassifier(verbosity=2, generations=5, max_time_mins=10, population_size=30)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_pipeline.py')

Generation 1 - Current best internal CV score: 0.74296788482835

Generation 2 - Current best internal CV score: 0.7616832779623477

Generation 3 - Current best internal CV score: 0.7616832779623477

Generation 4 - Current best internal CV score: 0.7616832779623477

Generation 5 - Current best internal CV score: 0.7616832779623477

Best pipeline: LogisticRegression(input_matrix, C=1.0, dual=False, penalty=l2)
0.7065217391304348

In [40]:
X_train

,years_to_birth,gender,14-3-3_beta_p,14-3-3_epsilon_p,14-3-3_zeta_p,4E-BP1_p,4E-BP1_pS65_p,4E-BP1_pT37_T46_p,4E-BP1_pT70_p,53BP1_p,...,p27_p,p27_pT157_p,p27_pT198_p,p38_pT180_Y182_p,p53_p,p62-LCK-ligand_p,p70S6K_p,p70S6K_pT389_p,p90RSK_p,p90RSK_pT359_S363_p
128,31,0,0.256186,0.351806,0.296820,0.218547,0.037397,-0.338240,0.244420,-0.149193,...,0.305345,0.000000,-0.058761,-0.351028,0.007165,0.191062,0.040448,-0.797395,-0.572443,-0.003628
151,30,1,-0.191855,-0.278814,-0.078937,0.740920,0.542324,0.995317,0.648577,0.795540,...,-0.119850,0.099766,-0.002087,-0.102062,0.007994,-0.317128,0.072470,-0.586471,-0.636580,-0.208996
19,52,0,0.069545,0.104028,0.301267,0.172697,-0.315924,-1.125112,-0.130154,-0.047945,...,0.222324,0.107073,0.195001,0.340722,-0.178160,-0.484619,0.177603,-0.711283,-0.384511,0.054690
126,34,1,0.675358,-0.370391,1.159914,-0.313542,0.832579,0.755965,0.176486,0.045290,...,-0.123337,-0.098464,-0.093290,-0.084571,-0.111389,-0.207131,0.084117,1.486272,-0.440519,-0.068734
98,34,0,-0.101373,0.524655,-0.368352,0.163717,-0.321998,0.584975,-0.274333,-0.175265,...,0.200348,-0.133055,0.061035,0.288925,0.067129,-0.133345,-0.137586,-1.043472,-0.435468,0.154620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,52,0,-0.146375,-0.073627,0.014565,0.056742,-0.133108,-0.175908,-0.103202,0.307380,...,-0.183561,-0.030379,0.034950,0.130722,-0.617652,-0.022638,-0.012565,-0.146269,0.080265,-0.155376
51,30,0,-0.086881,-0.066812,-0.126120,-0.073413,0.166998,0.505592,-0.048439,0.134150,...,-0.327608,-0.061743,-0.117287,0.019627,0.035272,-0.145070,-0.090996,0.528735,-0.078728,0.038975
17,29,0,-0.224992,-0.005634,-0.375402,0.173940,-0.306134,0.020065,-0.277527,0.382499,...,-0.112993,-0.107617,0.065387,0.444670,-0.008788,-0.355260,0.046404,-1.152293,-0.213763,-0.045945
239,74,1,0.112185,0.517919,0.814777,-0.081526,0.082524,-0.825992,-0.010730,-0.112660,...,-0.044852,0.106016,0.037594,-0.068880,0.064956,0.251615,0.010696,0.908965,0.251480,-0.118555
119,36,0,-0.020020,-0.050685,-0.024161,0.080534,0.228500,0.784488,0.050744,0.477637,...,-0.029669,-0.146004,-0.146018,0.464889,-0.247970,-0.215752,-0.073867,-0.737987,-0.292291,0.029348